DISTRO_IDS = ['2x', '4mlinux', '64studio', 'absolute', 'abuledu', 'adamantix',
              'adios', 'admelix', 'agilia', 'aleader', 'alinex', 'alinux',
              'alixe', 'alpine', 'alt', 'amaroklive', 'amber', 'androidx86',
              'ankur', 'annvix', 'annyung', 'anonymos', 'antemium', 'antergos',
              'antix', 'antomic', 'apodio', 'aptosid', 'arabbix', 'arabian',
              'arch', 'archbang', 'archeos', 'archie', 'ares', 'arios', 'ark',
              'artistx', 'arudius', 'asianlinux', 'asianux', 'aslinux', 'asp',
              'astaro', 'asterisknow', 'asturix', 'athene', 'atmission',
              'atomix', 'augustux', 'aurora', 'auroraos', 'aurox', 'austrumi',
              'avlinux', 'ayrsoft', 'b2d', 'backbox', 'backtrack', 'baltix',
              'bardinux', 'bayanihan', 'beafanatix', 'beakos', 'bearops',
              'beatrix', 'bee', 'beehive', 'beernix', 'belenix', 'berry',
              'biadix', 'bicom', 'biglinux', 'bintoo', 'biobrew', 'bioknoppix',
              'biolinux', 'blackpanther', 'blackrhino', 'blag', 'blankon',
              'blin', 'blue', 'bluepoint', 'bluewall', 'bluewhite64', 'bodhi',
              'bonzai', 'boss', 'boten', 'bridge', 'brlix', 'brlspeak',
              'bsdanywhere', 'buffalo', 'bulinux', 'burapha', 'byo',
              'byzantineos', 'cae', 'caine', 'caixamagica', 'calculate',
              'canaima', 'caos', 'catix', 'ccux', 'cdlinux', 'censornet',
              'centos', 'centrych', 'chakra', 'chinese2000', 'chitwanix',
              'cinnarch', 'clarkconnect', 'cle', 'clearos', 'clonezilla',
              'clusterix', 'clusterknoppix', 'cobind', 'college', 'comfusion',
              'commodore', 'condorux', 'conectiva', 'connochaet', 'cool',
              'core', 'corel', 'coyote', 'cpubuilders', 'crunchbang', 'crux',
              'ctkarch', 'damnsmall', 'danix', 'darkstar', 'debian', 'debris',
              'debxpde', 'deepin', 'deepwater', 'defender', 'definity', 'deft',
              'deli', 'demolinux', 'demudi', 'descentos', 'desktopbsd',
              'devil', 'digantel', 'discoverstation', 'dizinha', 'dnalinux',
              'doudou', 'draco', 'dragonflybsd', 'dragora', 'dreamlinux',
              'dreamstudio', 'drinou', 'dvl', 'dynasoft', 'dynebolic',
              'dzongkha', 'eadem', 'eagle', 'earos', 'easypeasy', 'easys',
              'ebox', 'edubuntu', 'eduknoppix', 'edulinux', 'ehad', 'ekaaty',
              'elastix', 'elearnix', 'element', 'elementary', 'elive',
              'elpicx', 'elx', 'emmabuntus', 'endian', 'engarde', 'epidemic',
              'eridani', 'erposs', 'estrellaroja', 'esun', 'esware',
              'euronode', 'everest', 'evilentity', 'evinux', 'exe', 'extix',
              'ezplanet', 'famelix', 'faunos', 'feather', 'featherweight',
              'fedora', 'fermi', 'finnix', 'fire', 'firefly', 'flash',
              'flonix', 'fluxbuntu', 'foresight', 'fork', 'forlex', 'fox',
              'freebsd', 'freedows', 'freeduc', 'freeducsup', 'freenas',
              'freepia', 'freesbie', 'freespire', 'frenzy', 'frugalware',
              'ftosx', 'fuduntu', 'fuguita', 'funtoo', 'fusion', 'geexbox',
              'gelecek', 'genieos', 'gentoo', 'gentooth', 'gentoox',
              'geolivre', 'ghostbsd', 'gibraltar', 'ging', 'gnacktrack',
              'gnewsense', 'gnix', 'gnobsd', 'gnoppix', 'gnox', 'gnustep',
              'goblinx', 'gobo', 'gos', 'gparted', 'grafpup', 'granular',
              'greenie', 'grml', 'guadalinex', 'gulicbsd', 'h3knix',
              'haansoft', 'hacao', 'haiku', 'hakin9', 'hancom', 'hanthana',
              'happy', 'happymac', 'haydar', 'hedinux', 'helix', 'heretix',
              'hikarunix', 'hispafuentes', 'hiweed', 'hklpg', 'holon',
              'honeywall', 'howtux', 'hpsecure', 'hybryde', 'hymera', 'ibox',
              'icepack', 'ichthux', 'idms', 'igelle', 'ignalum', 'imagicos',
              'imagineos', 'immunix', 'impi', 'incognito', 'indlinux',
              'inquisitor', 'insert', 'insigne', 'ipcop', 'ipfire', 'iqunix',
              'jacklab', 'jamd', 'jblinux', 'jibbed', 'jolicloud', 'jolinux',
              'jolios', 'jollix', 'julex', 'jusix', 'k12linux', 'k12ltsp',
              'kaella', 'kahelos', 'kalango', 'kali', 'kanotix', 'kaos',
              'karamad', 'karoshi', 'kate', 'kdemar', 'kinneret', 'kiwi',
              'klax', 'klikit', 'klustrix', 'kmlinux', 'knopils', 'knoppel',
              'knopperdisk', 'knoppix', 'knoppix64', 'knoppixmame',
              'knoppmyth', 'knosciences', 'kolibri', 'komodo', 'kondara',
              'kongoni', 'kore', 'korora', 'kororaa', 'krud', 'kubuntu',
              'kuki', 'kurumin', 'kwheezy', 'kwort', 'lamppix', 'las',
              'laser5', 'leeenux', 'legacy', 'lfs', 'lg3d', 'lgis', 'liberte',
              'libranet', 'liis', 'linare', 'lindows', 'lineox', 'linespa',
              'linex', 'linguasos', 'linhes', 'linnexos', 'linpus', 'linspire',
              'linuxbbq', 'linuxconsole', 'linuxeducd', 'linuxfx',
              'linuxgamers', 'linuxin', 'linuxinstall', 'linuxo', 'linuxplus',
              'linuxppc', 'linuxtle', 'linuxxp', 'linvo', 'liquidlemur',
              'lite', 'litrix', 'livecdrouter', 'livux', 'llgp', 'lliurex',
              'lnxbbc', 'loco', 'lonix', 'lorma', 'lps', 'lrs', 'lubuntu',
              'luinux', 'luit', 'luminux', 'lunar', 'luninux', 'lxle',
              'lycoris', 'macpup', 'madbox', 'madeinlinux', 'mageia', 'magic',
              'makulu', 'mandows', 'mandriva', 'mangaka', 'manjaro', 'maryan',
              'masonux', 'matriux', 'max', 'mayix', 'mcnlive', 'medialab',
              'meego', 'mepis', 'merdeka', 'midnightbsd', 'miko', 'milax',
              'minino', 'minislack', 'minix', 'mint', 'miracle', 'miros',
              'mizi', 'moblin', 'mockup', 'molinux', 'momonga', 'monomaxos',
              'monoppix', 'monowall', 'moonos', 'mops', 'morphix', 'movix',
              'msc', 'mumi', 'munjoy', 'muriqui', 'murix', 'musix',
              'mutagenix', 'myah', 'mylinux', 'myrinix', 'mythbuntu',
              'mythdora', 'nanolinux', 'nas4free', 'nasgaia', 'natures',
              'navynos', 'neat', 'neoshine', 'nepalinux', 'netbsd',
              'netrunner', 'netsecl', 'netwosix', 'nexenta', 'nexentastor',
              'niigata', 'nimblex', 'nitix', 'nix', 'nixos', 'nonux',
              'nordisknoppix', 'nova', 'novell', 'nst', 'nubuntu', 'nutyx',
              'nuxone', 'oeone', 'ogoknoppix', 'ojuba', 'olive', 'olivebsd',
              'olpc', 'omoikane', 'onebase', 'onet', 'openbsd', 'opendesktop',
              'openelec', 'openfiler', 'opengeu', 'openindiana', 'openlab',
              'openlx', 'openmamba', 'openmandriva', 'openmediavault',
              'openna', 'opensolaris', 'openwall', 'ophcrack', 'oracle',
              'oralux', 'os4', 'otakux', 'overclockix', 'ozos', 'ozunity',
              'paipix', 'paldo', 'papug', 'parabola', 'pardus', 'parsix',
              'parslinux', 'partedmagic', 'pcbsd', 'pclinuxos', 'pcos',
              'peachtree', 'pear', 'pelicanhpc', 'penguinsleuth', 'pentoo',
              'peppermint', 'pequelin', 'pfsense', 'phaeronix', 'phayoune',
              'phinx', 'phlak', 'phpsol', 'pibang', 'pidora', 'piebox',
              'pilot', 'pingo', 'pinguy', 'pingwinek', 'pioneer', 'plamo',
              'planb', 'pld', 'plop', 'point', 'polarbear', 'poliarch',
              'porteus', 'poseidon', 'pqui', 'privatix', 'progeny', 'progex',
              'projectdev', 'protech', 'proxmox', 'pud', 'puppy', 'puredyne',
              'pureos', 'q4os', 'qilinux', 'qimo', 'qomo', 'quantian', 'qubes',
              'quirky', 'railslive', 'raspbian', 'raspbmc', 'reactos',
              'rebellin', 'redflag', 'redhat', 'redo', 'redoffice', 'redwall',
              'remnux', 'resala', 'rescatux', 'resulinux', 'rip', 'risc',
              'robolinux', 'rock', 'rockscluster', 'rofreesbie', 'root',
              'rosa', 'roslims', 'rpath', 'rpmlive', 'rubix', 'runt', 'runtu',
              'sabayon', 'sabily', 'salentos', 'saline', 'salix', 'saluki',
              'salvare', 'sam', 'samity', 'santafe', 'satux', 'saxenos',
              'schillix', 'sci', 'scientific', 'sco', 'securepoint',
              'semplice', 'sentinix', 'sentryfirewall', 'shabdix', 'shark',
              'shift', 'siduction', 'sidux', 'simplicity', 'skolelinux',
              'slackel', 'slackintosh', 'slackware', 'slamd64', 'slampp',
              'slavix', 'slax', 'sle', 'slitaz', 'slix', 'slotech', 'slynux',
              'smartos', 'smartpeer', 'smeserver', 'smoothwall', 'sms',
              'snappix', 'snofrix', 'snowlinux', 'sol', 'solaris', 'solusos',
              'solydxk', 'sophos', 'sorcerer', 'sot', 'sourcemage', 'soyombo',
              'sparky', 'spectra', 'sphinxos', 'sprezzos', 'springdale',
              'squiggleos', 'stampede', 'startcom', 'startos', 'std',
              'steamos', 'stella', 'storm', 'stresslinux', 'stux', 'sulix',
              'sunjds', 'sunwah', 'supergamer', 'superos', 'superrescue',
              'superx', 'suriyan', 'suse', 'swecha', 'swift', 'syllable',
              'symphony', 'systemrescue', 't2', 'ta', 'tablix', 'tails',
              'tanglu', 'tangostudio', 'tao', 'taprobane', 'tech', 'teenpup',
              'tfm', 'thepacketmaster', 'thinstation', 'thisk', 'thiz',
              'tilix', 'tinycore', 'tinyme', 'tinysofa', 'toorox',
              'topologilinux', 'toutou', 'triance', 'trinity', 'trisquel',
              'trixbox', 'troppix', 'truebsd', 'trustix', 'truva', 'trx',
              'tugux', 'tumix', 'tupiserver', 'tuquito', 'turbolinux',
              'turkix', 'turnkey', 'uberstudent', 'ubuntu', 'ubuntuce',
              'ubuntudp', 'ubuntugnome', 'ubuntukylin', 'ubuntume', 'ubuntupr',
              'ubunturescue', 'ubuntustudio', 'ufficiozero', 'uhu', 'ulite',
              'ulteo', 'ultima', 'ultimate', 'underground', 'united', 'unity',
              'univention', 'untangle', 'uos', 'userful', 'userlinux', 'ututo',
              'vast', 'vector', 'venenux', 'videolinux', 'vine', 'vinux',
              'virtual', 'virux', 'vixta', 'vlos', 'vmknoppix', 'vnlinux',
              'voltalinux', 'volumio', 'voodoo', 'vortexbox', 'voyager',
              'vyatta', 'wattos', 'wazobia', 'webconverger', 'whitebox',
              'whoppix', 'wienux', 'wifislax', 'winbi', 'wmlive', 'wolvix',
              'womp', 'wow', 'xandros', 'xange', 'xarnoppix', 'xevian', 'xfld',
              'xos', 'xpud', 'xteam', 'xubuntu', 'yellowdog', 'ylmf', 'yoper',
              'youresale', 'zen', 'zencafe', 'zenix', 'zentyal', 'zenwalk',
              'zerahstar', 'zeroshell', 'zeus', 'zevenos', 'zonecd', 'zopix',
              'zorin']
